version: '3'

services:
  go-server:
    env_file:
      - default_vars.env
    build: .
    ports:
      - "5000:5000"
    depends_on:
     - postgres
  postgres:
    env_file:
      - postgres.env
    image: postgres:13.3
    volumes: 
      - .:/docker-entrypoint-initdb.d
    expose:
      - "5432"
    ports:
      - "5432:5432"